### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by azmaktr**

### CODE REVIEW

**Review by husyn — APPROVED** [review]
LGTM

**Comment by husyn** [comment]
@azmaktr can we merge this?

**Comment by azmaktr** [comment]
@Rubix982 This is to put a checkmark on the github's standards for an open source repository.

We can perhaps have both of them at the same time.

**Comment by azmaktr** [comment]
@husyn Merged

**Comment by Rubix982** [comment]
@azmaktr oh that, gotcha!

**Pull request merged**
